module.exports = {
  someSidebar: {
    'Getting Started': ['installation', 'theming', 'contributing'],
    Components: [
      'accordion',
      'activityIndicator',
      {
        type: 'category',
        label: 'Avatar',
        items: ['avatarIcon', 'avatarImage', 'avatarText'],
      },
      'badge',
      'button',
      'calendar',
      {
        type: 'category',
        label: 'Card',
        items: ['card', 'cardActions', 'cardContent', 'cardCover', 'cardTitle'],
      },
      'checkbox',
      'chip',
      'collapsible',
      'dateTimePicker',
      'divider',
      {
        type: 'category',
        label: 'Drawer',
        items: ['drawerSection', 'drawerItem'],
      },
      'iconButton',
      {
        type: 'category',
        label: 'Menu',
        items: ['menu', 'menuItem'],
      },
      'modal',
      {
        type: 'category',
        label: 'Portal',
        items: ['portal', 'portalHost'],
      },
      'progressBar',
      'provider',
      {
        type: 'category',
        label: 'RadioButton',
        items: ['radio', 'radioGroup'],
      },
      {
        type: 'category',
        label: 'RichRadio',
        items: ['richRadioGroup', 'richRadioItem'],
      },
      'segmentedControl',
      'slider',
      'switch',
      'textInput',
      'timePicker',
      'typography',
    ],
  },
};
